export interface IUsersData {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  status: "active" | "inactive" | "pending";
}

export const usersData: IUsersData[] = [
  {
    id: "usr001",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@email.com",
    status: "active",
  },
  {
    id: "usr002",
    firstName: "Emma",
    lastName: "Johnson",
    email: "emma.j@email.com",
    status: "active",
  },
  {
    id: "usr003",
    firstName: "Michael",
    lastName: "Brown",
    email: "m.brown@email.com",
    status: "inactive",
  },
  {
    id: "usr004",
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah.d@email.com",
    status: "pending",
  },
  {
    id: "usr005",
    firstName: "James",
    lastName: "Wilson",
    email: "j.wilson@email.com",
    status: "active",
  },
  {
    id: "usr006",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "l.anderson@email.com",
    status: "active",
  },
  {
    id: "usr007",
    firstName: "David",
    lastName: "Martinez",
    email: "d.martinez@email.com",
    status: "inactive",
  },
  {
    id: "usr008",
    firstName: "Jennifer",
    lastName: "Taylor",
    email: "j.taylor@email.com",
    status: "active",
  },
  {
    id: "usr009",
    firstName: "Robert",
    lastName: "Thomas",
    email: "r.thomas@email.com",
    status: "pending",
  },
  {
    id: "usr010",
    firstName: "Maria",
    lastName: "Garcia",
    email: "m.garcia@email.com",
    status: "active",
  },
  {
    id: "usr011",
    firstName: "William",
    lastName: "Moore",
    email: "w.moore@email.com",
    status: "active",
  },
  {
    id: "usr012",
    firstName: "Elizabeth",
    lastName: "Jackson",
    email: "e.jackson@email.com",
    status: "inactive",
  },
  {
    id: "usr013",
    firstName: "Christopher",
    lastName: "White",
    email: "c.white@email.com",
    status: "active",
  },
  {
    id: "usr014",
    firstName: "Patricia",
    lastName: "Harris",
    email: "p.harris@email.com",
    status: "pending",
  },
  {
    id: "usr015",
    firstName: "Joseph",
    lastName: "Clark",
    email: "j.clark@email.com",
    status: "active",
  },
  {
    id: "usr016",
    firstName: "Margaret",
    lastName: "Lewis",
    email: "m.lewis@email.com",
    status: "active",
  },
  {
    id: "usr017",
    firstName: "Charles",
    lastName: "Lee",
    email: "c.lee@email.com",
    status: "inactive",
  },
  {
    id: "usr018",
    firstName: "Sandra",
    lastName: "Walker",
    email: "s.walker@email.com",
    status: "active",
  },
  {
    id: "usr019",
    firstName: "Thomas",
    lastName: "Hall",
    email: "t.hall@email.com",
    status: "pending",
  },
  {
    id: "usr020",
    firstName: "Nancy",
    lastName: "Allen",
    email: "n.allen@email.com",
    status: "active",
  },
  {
    id: "usr021",
    firstName: "Daniel",
    lastName: "Young",
    email: "d.young@email.com",
    status: "active",
  },
  {
    id: "usr022",
    firstName: "Betty",
    lastName: "King",
    email: "b.king@email.com",
    status: "inactive",
  },
  {
    id: "usr023",
    firstName: "Paul",
    lastName: "Wright",
    email: "p.wright@email.com",
    status: "active",
  },
  {
    id: "usr024",
    firstName: "Karen",
    lastName: "Lopez",
    email: "k.lopez@email.com",
    status: "pending",
  },
  {
    id: "usr025",
    firstName: "Mark",
    lastName: "Hill",
    email: "m.hill@email.com",
    status: "active",
  },
  {
    id: "usr026",
    firstName: "Linda",
    lastName: "Scott",
    email: "l.scott@email.com",
    status: "active",
  },
  {
    id: "usr027",
    firstName: "Donald",
    lastName: "Green",
    email: "d.green@email.com",
    status: "inactive",
  },
  {
    id: "usr028",
    firstName: "Helen",
    lastName: "Adams",
    email: "h.adams@email.com",
    status: "active",
  },
  {
    id: "usr029",
    firstName: "George",
    lastName: "Baker",
    email: "g.baker@email.com",
    status: "pending",
  },
  {
    id: "usr030",
    firstName: "Donna",
    lastName: "Nelson",
    email: "d.nelson@email.com",
    status: "active",
  },
  {
    id: "usr031",
    firstName: "Kenneth",
    lastName: "Carter",
    email: "k.carter@email.com",
    status: "active",
  },
  {
    id: "usr032",
    firstName: "Carol",
    lastName: "Mitchell",
    email: "c.mitchell@email.com",
    status: "inactive",
  },
  {
    id: "usr033",
    firstName: "Steven",
    lastName: "Perez",
    email: "s.perez@email.com",
    status: "active",
  },
  {
    id: "usr034",
    firstName: "Michelle",
    lastName: "Roberts",
    email: "m.roberts@email.com",
    status: "pending",
  },
  {
    id: "usr035",
    firstName: "Edward",
    lastName: "Turner",
    email: "e.turner@email.com",
    status: "active",
  },
  {
    id: "usr036",
    firstName: "Laura",
    lastName: "Phillips",
    email: "l.phillips@email.com",
    status: "active",
  },
  {
    id: "usr037",
    firstName: "Ronald",
    lastName: "Campbell",
    email: "r.campbell@email.com",
    status: "inactive",
  },
  {
    id: "usr038",
    firstName: "Sarah",
    lastName: "Parker",
    email: "s.parker@email.com",
    status: "active",
  },
  {
    id: "usr039",
    firstName: "Larry",
    lastName: "Evans",
    email: "l.evans@email.com",
    status: "pending",
  },
  {
    id: "usr040",
    firstName: "Kimberly",
    lastName: "Edwards",
    email: "k.edwards@email.com",
    status: "active",
  },
  {
    id: "usr041",
    firstName: "Timothy",
    lastName: "Collins",
    email: "t.collins@email.com",
    status: "active",
  },
  {
    id: "usr042",
    firstName: "Deborah",
    lastName: "Stewart",
    email: "d.stewart@email.com",
    status: "inactive",
  },
  {
    id: "usr043",
    firstName: "Jeffrey",
    lastName: "Morris",
    email: "j.morris@email.com",
    status: "active",
  },
  {
    id: "usr044",
    firstName: "Melissa",
    lastName: "Rogers",
    email: "m.rogers@email.com",
    status: "pending",
  },
  {
    id: "usr045",
    firstName: "Gary",
    lastName: "Reed",
    email: "g.reed@email.com",
    status: "active",
  },
  {
    id: "usr046",
    firstName: "Sharon",
    lastName: "Cook",
    email: "s.cook@email.com",
    status: "active",
  },
  {
    id: "usr047",
    firstName: "Stephen",
    lastName: "Morgan",
    email: "s.morgan@email.com",
    status: "inactive",
  },
  {
    id: "usr048",
    firstName: "Cynthia",
    lastName: "Bell",
    email: "c.bell@email.com",
    status: "active",
  },
  {
    id: "usr049",
    firstName: "Eric",
    lastName: "Murphy",
    email: "e.murphy@email.com",
    status: "pending",
  },
  {
    id: "usr050",
    firstName: "Kathleen",
    lastName: "Bailey",
    email: "k.bailey@email.com",
    status: "active",
  },
];
